chore: Convert gitmodule to https
Otherwise, when adding the repository as a git dependency to a Rust
project one can get cargo errors like:

```
error: failed to get `jsonschema` as a dependency of package `jsonschema-validator v0.1.0 (/home/leo/Projekte/jsonschema-validator)`

Caused by:
  failed to load source for dependency `jsonschema`

Caused by:
  Unable to update https://github.com/leoschwarz/jsonschema-rs?branch=v0.2.0-disable_tls

Caused by:
  failed to update submodule `tests/suite`

Caused by:
  failed to fetch submodule `tests/suite` from git@github.com:json-schema-org/JSON-Schema-Test-Suite.git

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded
```